#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libvma
Version  : 9.4.0
Release  : 10
URL      : https://github.com/Mellanox/libvma/archive/9.4.0/libvma-9.4.0.tar.gz
Source0  : https://github.com/Mellanox/libvma/archive/9.4.0/libvma-9.4.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0
Requires: libvma-bin = %{version}-%{release}
Requires: libvma-lib = %{version}-%{release}
Requires: libvma-license = %{version}-%{release}
Requires: libvma-man = %{version}-%{release}
BuildRequires : bison
BuildRequires : flex
BuildRequires : glibc-bin
BuildRequires : libcap-dev
BuildRequires : libnl-dev
BuildRequires : rdma-core-dev
BuildRequires : valgrind
Patch1: 0001-Work-around-build-failure-on-recvmmsg-redefined.patch

%description
Update: 12 Aug 2018
Introduction
============
Mellanox's Messaging Accelerator (VMA) is dynamically linked user space Linux
library for transparently enhancing the performance of networking-heavy
applications. It boosts performance for message-based and streaming applications
such as those found in financial services market data environments and Web2.0
clusters.
It allows application written over standard socket API to run over Infiniband
and/or Ethernet from user-space with full network stack bypass.
The result is a reduction in latency by as much as 300%,
an increase in application throughput by as much as 200%,
higher packets rates and better CPU utilization as compared to applications
running on standard Ethernet or InfiniBand interconnect networks.

%package bin
Summary: bin components for the libvma package.
Group: Binaries
Requires: libvma-license = %{version}-%{release}

%description bin
bin components for the libvma package.


%package dev
Summary: dev components for the libvma package.
Group: Development
Requires: libvma-lib = %{version}-%{release}
Requires: libvma-bin = %{version}-%{release}
Provides: libvma-devel = %{version}-%{release}
Requires: libvma = %{version}-%{release}

%description dev
dev components for the libvma package.


%package doc
Summary: doc components for the libvma package.
Group: Documentation
Requires: libvma-man = %{version}-%{release}

%description doc
doc components for the libvma package.


%package lib
Summary: lib components for the libvma package.
Group: Libraries
Requires: libvma-license = %{version}-%{release}

%description lib
lib components for the libvma package.


%package license
Summary: license components for the libvma package.
Group: Default

%description license
license components for the libvma package.


%package man
Summary: man components for the libvma package.
Group: Default

%description man
man components for the libvma package.


%prep
%setup -q -n libvma-9.4.0
cd %{_builddir}/libvma-9.4.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1633447924
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1633447924
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libvma
cp %{_builddir}/libvma-9.4.0/COPYING %{buildroot}/usr/share/package-licenses/libvma/58d2b9d325c8b15fdd743be2040c275350091bf4
cp %{_builddir}/libvma-9.4.0/tests/gtest/googletest/LICENSE %{buildroot}/usr/share/package-licenses/libvma/5a2314153eadadc69258a9429104cd11804ea304
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/vma_stats
/usr/bin/vmad

%files dev
%defattr(-,root,root,-)
/usr/include/mellanox/vma_extra.h
/usr/lib64/libvma.so

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/libvma/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libvma.so.9
/usr/lib64/libvma.so.9.4.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libvma/58d2b9d325c8b15fdd743be2040c275350091bf4
/usr/share/package-licenses/libvma/5a2314153eadadc69258a9429104cd11804ea304

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man7/vma.7
/usr/share/man/man8/vma_stats.8
/usr/share/man/man8/vmad.8
